name: Crowdin Upload Files

on:
  workflow_dispatch:

jobs:
  upload:
    name: Upload Files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Upload Files
      env:
        CROWDIN_AUTH_TOKEN: ${{ secrets.ZAPBOT_CROWDIN_TOKEN }}
      run: ./gradlew crowdinUploadSourceFiles
