name: Prepare Release Add-on

on:
  workflow_dispatch:

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Prepare Release and Create Pull Request
      env:
        ZAPBOT_TOKEN: ${{ secrets.ZAPBOT_TOKEN }}
      run: ./gradlew createPullRequestRelease
